name: MCP Token Analysis
description: Analyze token usage of MCP servers and compare against baselines
author: Ben Sully

branding:
  icon: bar-chart-2
  color: orange

inputs:
  command:
    description: Command to start the MCP server
    required: true
  baseline:
    description: Path to baseline JSON file for comparison
    required: false
  threshold-percent:
    description: Maximum allowed percentage increase in tokens
    required: false
    default: "5"
  threshold-absolute:
    description: Maximum allowed absolute increase in tokens
    required: false
  anthropic-api-key:
    description: Anthropic API key for accurate token counting (falls back to tiktoken if not provided)
    required: false
  provider:
    description: Token counting provider (anthropic or tiktoken). Auto-detects if not specified.
    required: false
  model:
    description: Model to use for token counting
    required: false
  all-providers:
    description: Generate baseline with all available providers for cross-environment compatibility
    required: false
    default: "false"
  output:
    description: Path to save the report JSON
    required: false
  timeout:
    description: Timeout in seconds for server startup
    required: false
    default: "30"
  version:
    description: Version of mcp-tokens to use
    required: false
    default: latest
  comment:
    description: Post a PR comment with results (requires github-token for PRs)
    required: false
    default: "false"
  comment-on-pass:
    description: Post a comment even when the check passes (only applies when comment is true)
    required: false
    default: "false"
  max-tool-changes:
    description: Maximum number of tool changes to show in PR comment (0 for all)
    required: false
    default: "5"
  github-token:
    description: GitHub token for posting PR comments (required if comment is true)
    required: false

outputs:
  total-tokens:
    description: Total token count
    value: ${{ steps.analyze.outputs.total-tokens }}
  tool-tokens:
    description: Token count for tools only
    value: ${{ steps.analyze.outputs.tool-tokens }}
  provider:
    description: Token counting provider used
    value: ${{ steps.analyze.outputs.provider }}
  diff:
    description: Token difference from baseline
    value: ${{ steps.analyze.outputs.diff }}
  diff-percent:
    description: Percentage difference from baseline
    value: ${{ steps.analyze.outputs.diff-percent }}
  passed:
    description: Whether the threshold check passed
    value: ${{ steps.analyze.outputs.passed }}
  failure-reason:
    description: Human-readable failure reason if threshold exceeded
    value: ${{ steps.analyze.outputs.failure-reason }}
  baseline-tokens:
    description: Token count from baseline (for comparison)
    value: ${{ steps.analyze.outputs.baseline-tokens }}
  tool-changes:
    description: JSON array of tool changes (added/removed/modified tools with token diffs)
    value: ${{ steps.analyze.outputs.tool-changes }}
  tool-changes-count:
    description: Number of tools that changed
    value: ${{ steps.analyze.outputs.tool-changes-count }}

runs:
  using: composite
  steps:
    - name: Install mcp-tokens
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ github.token }}
      run: ${{ github.action_path }}/install.sh "$VERSION"

    - name: Run analysis
      id: analyze
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        MCP_TOKENS_PROVIDER: ${{ inputs.provider }}
        MCP_TOKENS_MODEL: ${{ inputs.model }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_BASELINE: ${{ inputs.baseline }}
        INPUT_THRESHOLD_PERCENT: ${{ inputs.threshold-percent }}
        INPUT_THRESHOLD_ABSOLUTE: ${{ inputs.threshold-absolute }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_ALL_PROVIDERS: ${{ inputs.all-providers }}
      run: ${{ github.action_path }}/analyze.sh

    - name: Post PR comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request' && (steps.analyze.outputs.passed == 'false' || inputs.comment-on-pass == 'true')
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PASSED: ${{ steps.analyze.outputs.passed }}
        TOTAL_TOKENS: ${{ steps.analyze.outputs.total-tokens }}
        BASELINE_TOKENS: ${{ steps.analyze.outputs.baseline-tokens }}
        DIFF: ${{ steps.analyze.outputs.diff }}
        DIFF_PERCENT: ${{ steps.analyze.outputs.diff-percent }}
        FAILURE_REASON: ${{ steps.analyze.outputs.failure-reason }}
        TOOL_CHANGES: ${{ steps.analyze.outputs.tool-changes }}
        MAX_TOOL_CHANGES: ${{ inputs.max-tool-changes }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: ${{ github.action_path }}/comment.sh

    - name: Check result
      shell: bash
      env:
        PASSED: ${{ steps.analyze.outputs.passed }}
      run: ${{ github.action_path }}/check.sh
